permalink: pretty
exclude: [node_modules]
keep_files: [assets/css]
collections:
  videos:
    output: true
    permalink: /videos/:path/
    title: Videos

defaults:
  -
    scope:
      path: ""
      type: "videos"
    values:
      layout: "video"