permalink: pretty
exclude: [node_modules]
keep_files: [assets/css]
title: PHP UK Conference
name: PHP UK Conference
url:
description: We are pleased to announce the 13th Annual PHP UK Conference. An optional workshop day followed by two days of amazing talks, plentiful networking opportunities and great socials. PHP UK offers the most up-to-date PHP information and training.
collections:
  videos:
    output: true
    permalink: /videos/:path/
    title: Videos

defaults:
  - scope:
      path: ""
      type: "videos"
    values:
      layout: "video"
  - scope:
      path: _videos/2016
    values:
      year: "2016"
  - scope:
      path: _videos/2015
    values:
      year: "2015"